doctrine_migrations:
    dir_name: "%campaignchain_deployment_update.generate_dir%"
    namespace: Application\Migrations
    table_name: campaignchain_deployment_update_schema
    name: Application Migrations